# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "activerecord", "~> 6.0", ">= 6.0.1"
gem "mysql2"
gem "composite_primary_keys"
gem "mongo", "~> 2.11"
gem "neo4j", "~> 9.6"
gem "rake"
gem "neo4j-rake_tasks"
